# SFA

## Importing libraries

In [1]:
# Data handling and manipulation
import numpy as np
import pandas as pd

# Data visualization
import matplotlib.pyplot as plt

# Statistical modeling and optimization
import statsmodels.api as sm
import optbinning as optb

## Importing development data

In [2]:
riskdiff_data = pd.read_csv("Data/riskdiff_data.csv")

In [3]:
train = riskdiff_data[riskdiff_data["port_type"] == "DEV"].copy()

In [4]:
dictionary = pd.read_csv("Data/data_dictionary.csv")

In [5]:
dictionary

,variable,group,availability,description
0,customer_id,observation_status,quarterly/current,customer id
1,quarter,observation_status,quarterly/current,quarter
2,observation_date,observation_status,quarterly/current,observation date
3,core_customer,observation_status,quarterly/current,core customer
4,sector,behavior_macro_or_ratios,quarterly/current,sector
...,...,...,...,...
123,debt_ke_growth_yoy,accounting_report,"annual, lagged",debt ke growth yoy
124,cash_ke_growth_yoy,accounting_report,"annual, lagged",cash ke growth yoy
125,equity_ke_growth_yoy,accounting_report,"annual, lagged",equity ke growth yoy
126,default_12m,target,Never use as predictor,default 12m
127,financial_report_age_quarters,behavior_macro_or_ratios,quarterly/current,financial report age quarters

In [6]:
var = dictionary[np.isin(dictionary["group"], ["behavior_macro_or_ratios"])]["variable"].tolist()

In [8]:
pd.DataFrame([train[var].dtypes, train[var].isna().sum()], index=['dtypes', 'na_count']).T

                                dtypes na_count
sector                             str        0
customer_age_years             float64        0
relationship_age_quarters        int64        0
credit_limit_ke                float64        0
ead_ke                         float64        0
...                                ...      ...
credit_limit_to_revenue        float64     2698
overdraft_to_limit             float64        0
cashflow_in_to_out             float64        0
cash_to_ead                    float64        0
financial_report_age_quarters  float64     2698

[85 rows x 2 columns]

In [ ]:
binning = {}

for v in var:
    if type(train[v][0]) == str:
        continue
    binning[v] = optb.OptimalBinning(name=v)
    print(v)
    binning[v].fit(train[v], train["default_12m"])

customer_age_years
relationship_age_quarters
credit_limit_ke
ead_ke
outstanding_balance_ke
utilization_pct
arrears_amount_ke
days_past_due_proxy
past_due_30d_count_12m
overdraft_events_12m
missed_payments_12m
max_utilization_12m_pct
utilization_change_3m_pct
limit_change_12m_pct
payment_delay_avg_days
payment_delay_max_days
external_delinquency_count
external_collection_case_count
external_payment_index
external_negative_notice
export_share_pct
rate_sensitivity
rate_exposure_ke
behavioral_cashflow_in_ke
behavioral_cashflow_out_ke
deposit_balance_ke
deposit_volatility_12m
transaction_count_q
days_since_last_payment
cash_flow_stress_score
sector_risk_exposure
gross_margin_behavior_proxy
gdp_yoy_proxy_pct
unemployment_proxy_pct
interest_rate_proxy_pct
inflation_proxy_pct
ebitda_margin
ebit_margin
net_profit_margin
roa
roe
return_on_capital
operating_cf_margin
gross_margin
asset_turnover
revenue_to_debt
ebitda_to_assets
cash_return_on_assets
equity_ratio
debt_to_assets
debt_to_equity
net_debt_to_ebitda
debt_to_ebitda
net_debt_to_assets
equity_to_debt
liabilities_to_equity
short_debt_ratio
long_debt_ratio
current_ratio
quick_ratio
cash_ratio
working_capital_to_assets
cash_to_assets
cash_to_debt
operating_cf_to_debt
operating_cf_to_current_liabilities
interest_coverage
ebitda_interest_coverage
receivables_days
payables_days
inventory_days
cash_conversion_cycle
inventory_turnover
receivable_turnover
working_capital_turnover
financial_debt_to_revenue
employees_log
revenues_log
ead_to_revenue
credit_limit_to_revenue
overdraft_to_limit
cashflow_in_to_out
cash_to_ead
financial_report_age_quarters